version: '3'
services:
  nginx:
    image: docker.io/nginx:1.29-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ~/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
  nano-iot:
    image: ghcr.io/hevali/nano-iot
    pull_policy: always
    ports:
      - '3000:3000'
    env_file: ~/nano-iot/.env
    environment:
      PORT: 3000
      NODE_ENV: production
    volumes:
      - ~/nano-iot/data:/data
